version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "localhost"
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_NAME: "crud_go"
    depends_on:
      - db
