version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8000
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - db-service
  
  db-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD="password"
    ports:
      - 3306
    volumes:
      - ./mysqldb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - app-network

networks:
 app-network:
  driver: bridge